// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFpt97N6LiRnyYyHxo_68_OAHrcJVUBBE',
    appId: '1:896235731512:web:f4956cb551f6b7aa6d44cd',
    messagingSenderId: '896235731512',
    projectId: 'cooksmart-f2f80',
    authDomain: 'cooksmart-f2f80.firebaseapp.com',
    storageBucket: 'cooksmart-f2f80.appspot.com',
    measurementId: 'G-RT7QFNNNZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlCIAnu37QN04AuQc56xhgRHUzqjWRCA',
    appId: '1:896235731512:android:e3dc3fb213754ee86d44cd',
    messagingSenderId: '896235731512',
    projectId: 'cooksmart-f2f80',
    storageBucket: 'cooksmart-f2f80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZDc6ogkZjMj7aNsoM1veDU_rI2fGC_M',
    appId: '1:896235731512:ios:08fe002abf2e87556d44cd',
    messagingSenderId: '896235731512',
    projectId: 'cooksmart-f2f80',
    storageBucket: 'cooksmart-f2f80.appspot.com',
    iosClientId: '896235731512-dk7puuisahdafttt4guqii4eua3tej0l.apps.googleusercontent.com',
    iosBundleId: 'com.techkitchen.cookbook',
  );

}